<a href="https://colab.research.google.com/github/drago467/AIVN-MODULE-3/blob/main/Data%20Visualization%20and%20Analysis%202/Advertising_FeatureSelection_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
%matplotlib qt
np.random.seed(123)

data = genfromtxt('advertising.csv', delimiter=',', skip_header=1)
print(data.shape)

np.random.shuffle(data)
print(data[:5])

(200, 4)
[[199.8   3.1  34.6  16.4]
 [ 80.2   0.    9.2  11.9]
 [ 74.7  49.4  45.7  14.7]
 [ 44.7  25.8  20.6  10.1]
 [147.3  23.9  19.1  14.6]]


In [ ]:
x = data[:,1:2]
y = data[:,3:]

max_value = np.max(x)
min_value = np.min(x)
avg = np.mean(x)
x = (x-avg) / (max_value-min_value)

x_b = np.c_[np.ones((200, 1)), x]
print(x_b[:5])

[[ 1.         -0.40653226]
 [ 1.         -0.46903226]
 [ 1.          0.52693548]
 [ 1.          0.05112903]
 [ 1.          0.01282258]]


In [ ]:
N = 150

x_train = x_b[:N]
y_train = y[:N]

x_test = x_b[N:]
y_test = y[N:]

print('x_train: ', x_train.shape)
print('y_train: ', y_train.shape)
print('x_test: ', x_test.shape)
print('y_test: ', y_test.shape)

x_train:  (150, 2)
y_train:  (150, 1)
x_test:  (50, 2)
y_test:  (50, 1)


## Train

In [ ]:
n_iterations = 150
learning_rate = 0.01

# khởi tạo giá trị tham số
thetas = np.random.randn(2, 1)
thetas_path = [thetas]
losses = []

for i in range(n_iterations):
    # tính output
    output = x_train.dot(thetas)

    # tính loss
    loss = (output - y_train)**2

    # tính đạo hàm cho loss
    loss_grd = 2*(output - y_train)/N

    # tính đạo hàm cho các tham số
    gradients = x_train.T.dot(loss_grd)

    # cập nhật tham số
    thetas = thetas - learning_rate*gradients
    thetas_path.append(thetas)

    mean_loss = np.sum(loss)/N
    losses.append(mean_loss)


# in loss cho 100 sample đầu
x_axis = list(range(n_iterations))
plt.plot(x_axis,losses[:n_iterations], color="r")
plt.show()

In [ ]:
print(thetas)
print('Loss: ', losses[-1])

[[14.178723  ]
 [ 1.12629254]]
Loss:  26.162301255736224


In [ ]:
# test

# tính output
output = x_test.dot(thetas)

# tính loss
loss = np.abs(output - y_test)
print('Test Loss: ', loss.mean())

Test Loss:  4.784831231429557
